### ISSUE TITLE
Media Queries dont accept comma separated $refs

### ISSUE THREAD

**Issue by monokee** [monokee/Sekoia#16]
```css
@media (max-width: 600px) {
  $self, $ref1, $ref2 {
    padding: 1em;
  }
}
```

Not working, refs aren't picked up.
